#!/bin/bash
# Generated by pmesod. Run from nXX/calib/ to create calculator inputs.
set -e
n_calib="${1:-99}"
case "$n_calib" in
  ""|*[!0-9]*) echo "Error: n_calib must be a positive integer."; exit 1 ;;
esac
if [ "$n_calib" -lt 1 ]; then echo "Error: n_calib must be positive."; exit 1; fi
filer=-1
script_dir="$(cd "$(dirname "$0")" && pwd)"
level_dir="$(cd "$script_dir/.." && pwd)"
project_dir="$(cd "$level_dir/.." && pwd)"
level_name="$(basename "$level_dir")"
work_dir="$script_dir/.genersod_work"
rm -rf "$work_dir"
mkdir -p "$work_dir/$level_name"
cp "$project_dir/INSOD" "$project_dir/supercell.cif" "$work_dir/"
for f in SGO EQMATRIX OPERATORS template_input.gin template_in.lammps template_castep.cell template_pw.in INCAR KPOINTS POTCAR; do
  [ -e "$project_dir/$f" ] && cp -R "$project_dir/$f" "$work_dir/"
done
for f in "$project_dir"/*.lib "$project_dir"/*.pot; do
  [ -e "$f" ] && cp "$f" "$work_dir/"
done
cp "$script_dir/ENSEMBLE" "$work_dir/$level_name/ENSEMBLE"
(cd "$work_dir" && genersod "$n_calib")
if compgen -G "$work_dir/$level_name/c*" > /dev/null; then
  cp -R "$work_dir/$level_name"/c* "$script_dir"/
fi
rm -rf "$work_dir"
job_sender="$script_dir/job_sender"
{
  echo "#!/bin/bash"
  echo "set -e"
  case "$filer" in
    1) echo 'GULP=${GULP:-gulp}'; echo 'for dir in c*/; do (cd "$dir" && $GULP < input.gin > output.gout); done' ;;
    11) echo 'VASP=${VASP:-vasp_std}'; echo 'for dir in c*/; do (cd "$dir" && $VASP > vasp.out); done' ;;
    12) echo 'for dir in c*/; do (cd "$dir" && castep castep); done' ;;
    13) echo 'PW=${PW:-pw.x}'; echo 'for dir in c*/; do (cd "$dir" && $PW < pw.in > pw.out); done' ;;
    *) echo 'echo "No calculator command is defined for this FILER."' ;;
  esac
} > "$job_sender"
chmod +x "$job_sender"
echo "Calibration inputs are in $script_dir/c*/"
